customers_api:
    resource: '@AppBundle/Controller/Customer'
    type: rest
    prefix: /customers

providers_api:
    resource: '@AppBundle/Controller/Provider'
    type: rest
    prefix: /providers