security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /login
                username_parameter: email
                password_parameter: password
                success_handler:  lexik_jwt_authentication.handler.authentication_success
                failure_handler:  lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            logout: true
        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }